### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by JudeNiroshan** [instructlab/sdg#294]
SDG process exit with error when using the `taxonomy_base` as `empty` in generate_data(). If I run without taxonomy_base empty, SDG completes without any error.

We used the original [instructlab taxonomy](https://github.com/instructlab/taxonomy) repository on main branch.

```
client: <openai.OpenAI object at 0x7fc8c1334890>
num_instructions_to_generate: 2
output_dir: /s3/ilab-...1289c0c83bd7/instructlab/67-da9be423f82e/sdg-op/sdg
taxonomy: /s3/ilab-...1289c0c83bd7/instructlab/e7-178c0220fc02/git-clone-op/taxonomy
taxonomy_base: empty
model_name: mistral
```

SDG process is being triggered inside a RHOAI pipeline component. 

```
[KFP Executor 2024-10-02 13:30:35,699 INFO]: HTTP Request: POST https://mistral.apps.ocp-...org/v1/completions "HTTP/1.1 200 OK"
[KFP Executor 2024-10-02 13:30:35,737 INFO]: Generated 3 samples
 
Map (num_proc=8):   0%|          | 0/10 [00:00<?, ? examples/s]
Map (num_proc=8):  50%|█████     | 5/10 [00:00<00:00, 45.54 examples/s]
Map (num_proc=8): 100%|██████████| 10/10 [00:00<00:00, 45.75 examples/s]
Map (num_proc=8): 100%|██████████| 10/10 [00:00<00:00, 31.63 examples/s]
 
Creating json from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]
Creating json from Arrow format: 100%|██████████| 1/1 [00:00<00:00, 243.53ba/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/app-root/lib64/python3.11/site-packages/kfp/dsl/executor_main.py", line 109, in <module>
    executor_main()
  File "/opt/app-root/lib64/python3.11/site-packages/kfp/dsl/executor_main.py", line 101, in executor_main
    output_file = executor.execute()
                  ^^^^^^^^^^^^^^^^^^
  File "/opt/app-root/lib64/python3.11/site-packages/kfp/dsl/executor.py", line 361, in execute
    result = self.func(**func_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.jf1GzHcUiD/ephemeral_component.py", line 40, in sdg_op
    generate_data(
  File "/opt/app-root/lib64/python3.11/site-packages/instructlab/sdg/generate_data.py", line 366, in generate_data
    samples = leaf_node_to_samples(leaf_node, server_ctx_size, chunk_word_count)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/app-root/lib64/python3.11/site-packages/instructlab/sdg/utils/taxonomy.py", line 332, in leaf_node_to_samples
    return _knowledge_leaf_node_to_samples(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/app-root/lib64/python3.11/site-packages/instructlab/sdg/utils/taxonomy.py", line 277, in _knowledge_leaf_node_to_samples
    chunking.chunk_document(
  File "/opt/app-root/lib64/python3.11/site-packages/instructlab/sdg/utils/chunking.py", line 46, in chunk_document
    no_tokens_per_doc = _num_tokens_from_words(chunk_word_count)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/app-root/lib64/python3.11/site-packages/instructlab/sdg/utils/chunking.py", line 17, in _num_tokens_from_words
    return int(num_words * 1.3)  # 1 word ~ 1.3 token
               ~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
I1002 13:30:38.148782      53 launcher_v2.go:153] publish success.
F1002 13:30:38.148996      53 main.go:51] failed to execute component: exit status 1
```

**Comment by bbrowning** [comment]
It looks like you're using SDG as a library here, right? You'll need to pass a value for the `chunk_word_count` parameter to `generate_data` to workaround this. It looks like we never tested this with a value of `None`, since when called from the CLI that value is always provided. The CLI defaults to a value of 1000 here, although you can raise that if you're working with a teacher model that has a larger context window.
